version: '3.8'

services:
  nfe-automator:
    build: .
    container_name: nfe_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - AGENT_TOKEN=chave-secreta-vps-123
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
